const mercado = require('./Mercado')
const produto = require('./Produto')

const p1 = new produto(1, "Arroz", "Arroz branco tipo 1", "Tio João", 50, 20.00)
const p2 = new produto(2, "Feijão", "Feijão carioca", "Camil", 30, 8.00)
const p3 = new produto(3, "Macarrão", "Macarrão espaguete", "Barilla", 20, 12.00)

const m1 = new mercado("Mercado Central", "12.345.678/0001-90", "Rua Principal, 123", "@mercadocentral", [])
m1.adicionarProduto(p1)
m1.adicionarProduto(p2)
m1.adicionarProduto(p3)
console.log(m1)
m1.imprimirProdutos()
console.log(`Valor total do mercado: R$${m1.calcularValorMercado().toFixed(2)}`)
m1.excluirProduto()
m1.imprimirProdutos()
console.log(`Valor total do mercado: R$${m1.calcularValorMercado().toFixed(2)}`)
m1.buscarProduto(2)
m1.encontrarProdutoMaisCaro()
m1.imprimir()
